jobs:
  build:
    name: Build and test Yauaa
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout sourcecode
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
    - continue-on-error: true
      name: Cache Local Maven Repository
      uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9
      with:
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        path: ~/.m2/repository
        restore-keys: '${{ runner.os }}-maven-

          '
    - continue-on-error: true
      name: 'Setup: Install JDK 8, 11, 17 & 21'
      uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9
      with:
        distribution: temurin
        java-version: '8

          11

          17

          21

          '
    - continue-on-error: true
      name: Build Yauaa
      run: ./mvnw clean install -PdisableDockerHubUsages
    - continue-on-error: true
      name: Codecov
      uses: codecov/codecov-action@c16abc29c95fcf9174b58eb7e1abf4c866893bc8
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
    - continue-on-error: true
      name: Ensure build is reproducible
      run: 'mkdir -p ../PreproducibleRebuildInDifferentDirectory

        cp -a . ../PreproducibleRebuildInDifferentDirectory

        cd ../PreproducibleRebuildInDifferentDirectory

        ./mvnw clean verify -PskipQuality -PartifactCompare

        # Remove the just installed artifacts to avoid blowing up the ~/.m2 cache.

        rm -rf ~/.m2/repository/nl/basjes/parse/useragent/

        '
name: Yauaa
on:
  repository_dispatch:
    types: trigger-ga___build.yml
permissions: read-all
