jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      with:
        fetch-depth: 0
        submodules: true
    - continue-on-error: true
      name: Setup Hugo
      uses: peaceiris/actions-hugo@16361eb4acea8698b220b76c0d4e84e1fd22c61d
      with:
        hugo-version: latest
    - continue-on-error: true
      name: Build
      run: cd documentation && hugo --minify
    - continue-on-error: true
      if: github.ref == 'refs/heads/main'
      name: Deploy
      uses: peaceiris/actions-gh-pages@373f7f263a76c20808c831209c920827a82a2847
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./documentation/public
name: Documentation Website
on:
  repository_dispatch:
    types: trigger-ga___website.yml
